---
title: This is the site title
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: This is the site description.
github_info:
  organization: 18F
  repository: uswds-jekyll
  default_branch: master
sass:
  style: compressed
